Controllers/AcademicosInstructorEduContinuaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SGCFIEE.Models;
using System.Diagnostics;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SGCFIEE.Controllers
{
    public class AcademicosInstructorEduContinuaController : Controller
    {
        //Función index, obtiene la información que se mostrara en la vista index del submodulo Intructor de educación continua.
        // GET: /<controller>/
        [Authorize] // vista principal
        public IActionResult Index()
        {
            List<TablaInstructorEduCont> ListInstructorEdu = new List<TablaInstructorEduCont>(); //Se crea una clase manualmente, para poder manipular la información con mayor facilidad.
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //De la clase creada, se genera la lista "ListInstructorEdu" la cual guardara la información obtenida de la consulta a continuación.
                ListInstructorEdu = (from instruc in context.RecursosExternos
                                        join acad in context.Academicos on instruc.IdAcademicos equals acad.IdAcademicos
                                        join perio in context.TipoPeriodo on instruc.IdPeriodo equals perio.IdPeriodo
                                        select new TablaInstructorEduCont
                                        {
                                            IdInstructorEdu = instruc.IdRecursosExternos,
                                            NumPersonal = acad.NumeroPersonal,
                                            Nombre = acad.Nombre,
                                            ApellidoPaterno = acad.ApellidoPaterno,
                                            ApellidoMaterno = acad.ApellidoMaterno,
                                            Ingreso = instruc.Ingreso,
                                            NomIngreso = instruc.Nombre,
                                            Periodo = perio.Nombre,
                                            Status = acad.Status
                                        }
                                    ).ToList();
            }
            return View(ListInstructorEdu); //Información retornada  a la vista.
        }
        //Función para obtener la información que llenara los select en la vista de crear.
        public IActionResult Crear()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                var acad = context.Academicos.ToList(); //Obtención de los académicos que se encuentran registrados en el sistema.
                var perio = context.TipoPeriodo.ToList(); //Obtención de los periodos que se encuentran registrados en el sistema.
                ViewData["academicos"] = acad; //Paso de los datos a la vista por el diccionario ViewData.
                ViewData["periodos"] = perio; //Paso de los datos a la vista por el diccionario ViewData.
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        //Función para guardar a los académicos que han hecho ingreso de recursos externos.
        public IActionResult GuardarInstructorEdu(RecursosExternos datos)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Se verifica que la información a guardar no este ya registrada en el sistema.
                var ListInstructorEdu = context.RecursosExternos.ToList();
                foreach (RecursosExternos item in ListInstructorEdu)
                {
                    //Comparación de los datos ha guardar y los datos ya registrados. 
                    if (datos.IdAcademicos == item.IdAcademicos && datos.IdPeriodo == item.IdPeriodo && datos.Nombre==item.Nombre && datos.Ingreso== item.Ingreso)
                    {
                        TempData["msg"] = "<script language='javascript'> swal({ title:'" + "La información ya se encuentra registrada!" + "', timer:'" + "3500" + "',type: '" + "info" + "', showConfirmButton: false })" + "</script>";
                        return RedirectToAction("Index");
                    }
                }
                //Guardado de los datos en la tabla RecursosExternos.
                context.RecursosExternos.Add(datos);
                context.SaveChanges();
                
            }
            //Alerta de guardado exitosamente.
            TempData["msg"] = "<script language='javascript'> swal({ title:'" + "Guardado exitosamente!" + "', timer:'" + "2000" + "',type: '" + "success" + "', showConfirmButton: false })" + "</script>";
            return RedirectToAction("Index"); //Regreso al index del submodulo.
        }
        //Función para obtener los datos que llenaran los input ha editar.
        public IActionResult Editar(int id)
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Consulta de los datos registrados en la base de datos.
                RecursosExternos DatosInstructorEdu = context.RecursosExternos.Where(s => s.IdRecursosExternos == id).Single();
                var perio = context.TipoPeriodo.ToList(); //Obtención de los periodos.
                var acad = context.Academicos.ToList(); //Obtención de los académicos.
                ViewData["periodos"] = perio; //Paso de los datos a la vista.
                ViewData["academicos"] = acad; //Paso de los datos a la vista.
                return View(DatosInstructorEdu);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        //Función que actualiza la información de los Instructores de eduacación continua.
        public IActionResult ActualizarInstructorEdu(RecursosExternos datos)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Verificación que los datos ha actualizar no esten ya registrados.
                var ListInstructorEdu = context.RecursosExternos.Where(y => y.IdRecursosExternos != datos.IdRecursosExternos).ToList();

                foreach (RecursosExternos item in ListInstructorEdu)
                {
                    //Se comparan que los datos ya registrados no sean iguales al actualizado.
                    if (datos.IdAcademicos == item.IdAcademicos && datos.IdPeriodo == item.IdPeriodo && datos.Nombre == item.Nombre && datos.Ingreso == item.Ingreso)
                    {
                        TempData["msg"] = "<script language='javascript'> swal({ title:'" + "La información ya se encuentra registrada!" + "', timer:'" + "3500" + "',type: '" + "info" + "', showConfirmButton: false })" + "</script>";
                        return RedirectToAction("Index");
                    }
                }
            }
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Actualizacion de los datos en la tabla.
                context.RecursosExternos.Update(datos);
                context.SaveChanges();
                TempData["msg"] = "<script language='javascript'> swal({ title:'" + "Actualizado exitosamente!" + "', timer:'" + "2000" + "',type: '" + "success" + "', showConfirmButton: false })" + "</script>"; //Mensaje de alerta.

            }
            return RedirectToAction("Index");
        }
        //Función para eliminara un registro de la tabla de Recursos Externos.
        public IActionResult Eliminar(int id)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Teniendo el id del registro a eliminar, se realiza la consulta de los datos.
                RecursosExternos eliminar = context.RecursosExternos.Where(w => w.IdRecursosExternos == id).Single();
                context.RecursosExternos.Remove(eliminar); //Eliminación del registro.
                context.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/AcademicosInstructorEduContinua/Crear.cshtml
@model SGCFIEE.Models.RecursosExternos;
@{
    ViewData["Title"] = "Crear";
    Layout = "~/Views/Home/Principal.cshtml";
    var acad = (IEnumerable<Academicos>)ViewData["academicos"];
    var perio = (IEnumerable<TipoPeriodo>)ViewData["periodos"];
}
<!DOCTYPE html>

<html>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card card-box">
                <div class="card-topline-green card-head">
                    <header>INSTRUCTOR DE EDUCACIÓN CONTINUA</header>        
                </div>
                <div class="card-body " id="bar-parent2">
                    <form asp-action="GuardarInstructorEdu" asp-antiforgery="true">
                        <div class="row">
                            <div class="col-md-6 col-md-6">
                                <div class="form-group">
                                    <label>Académico</label>
                                    <select asp-for="IdAcademicos" class="form-control">
                                        @foreach (var item in acad){
                                            <option value="@item.IdAcademicos">@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group" >
                                    <label>Periodo</label>
                                    <select asp-for="IdPeriodo" class="form-control">
                                        @foreach (var item in perio){
                                            <option value="@item.IdPeriodo">@Html.DisplayFor(modelItem => item.Nombre)</option>
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 col-md-6">
                                <div class="form-group">
                                    <label>Nombre del ingreso</label>
                                    <input asp-for="Nombre" type="text" class="form-control" placeholder="Ingresar..." required="required">
                                    <span asp-validation-for="Nombre" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>Cantidad de ingreso</label>
                                     <input asp-for="Ingreso" type="number" class="form-control" placeholder="Ingresar..." required="required">
                                    <span asp-validation-for="Ingreso" class="text-danger"></span>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-success btn-sm m-b-10" name="Guardar" style="float:right">
                                    Guardar
                                </button>
                                <a asp-controller="AcademicosInstructorEduContinua" asp-action="Index" class="btn btn-default btn-sm m-b-10" style="float:right">
                                Cancelar
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</html>

Views/AcademicosInstructorEduContinua/Editar.cshtml
@model SGCFIEE.Models.RecursosExternos;
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Home/Principal.cshtml";
    var acad = (IEnumerable<Academicos>)ViewData["academicos"];
    var perio = (IEnumerable<TipoPeriodo>)ViewData["periodos"];
}
<!DOCTYPE html>

<html>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card card-box">
                <div class="card-topline-green card-head">
                    <header>INSTRUCTOR DE EDUCACIÓN CONTINUA</header>        
                </div>
                <div class="card-body " id="bar-parent2">
                    <form asp-action="ActualizarInstructorEdu" asp-antiforgery="true">
                        <div class="row">
                            <input type="hidden" asp-for="IdRecursosExternos"/>
                            <div class="col-md-6 col-md-6">
                                <div class="form-group">
                                    <label>Académico</label>
                                    <select asp-for="IdAcademicos" class="form-control">
                                        @foreach (var item in acad)
                                        {
                                            @if (item.IdAcademicos != Model.IdAcademicos)
                                            {
                                                <option value="@item.IdAcademicos">@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</option>
                                            }
                                            else
                                            {
                                                <option selected value="@item.IdAcademicos">@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</option>
                                            }
                                        }
                                    </select>
                                </div>
                                <div class="form-group" >
                                    <label>Periodo</label>
                                     <select asp-for="IdPeriodo" class="form-control">
                                        @foreach (var item in perio)
                                        {
                                            @if (item.IdPeriodo != Model.IdPeriodo)
                                            {
                                                <option value="@item.IdPeriodo">@Html.DisplayFor(modelItem => item.Nombre)</option>
                                            }
                                            else
                                            {
                                                <option selected value="@item.IdPeriodo">@Html.DisplayFor(modelItem => item.Nombre)</option>
                                            }
                                        }
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6 col-md-6">
                                <div class="form-group">
                                    <label>Nombre del ingreso</label>
                                    <input asp-for="Nombre" type="text" placeholder="Ingresar..." class="form-control" required="required" value=@Model.Nombre>
                                    <span asp-validation-for="Nombre" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label>Cantidad de ingreso</label>
                                    <input asp-for="Ingreso" type="number" placeholder="Ingresar..." class="form-control" required="required" value=@Model.Ingreso>
                                    <span asp-validation-for="Ingreso" class="text-danger"></span>
                                </div>
                                <br>
                                <button type="submit" class="btn btn-success btn-sm m-b-10" name="Guardar" style="float:right">
                                    Guardar
                                </button>
                                <a asp-controller="AcademicosInstructorEduContinua" asp-action="Index" class="btn btn-default btn-sm m-b-10" style="float:right">
                                Cancelar
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</html>

Views/AcademicosInstructorEduContinua/Index.cshtml
@model  IEnumerable<SGCFIEE.Models.TablaInstructorEduCont>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Home/Principal.cshtml";
}
<script src="~/assets/js/pages/table/table_data.js"></script>
<link rel="stylesheet" href="~/assets/plugins/sweet-alert/sweetalert.min.css">
<script src="~/assets/plugins/sweet-alert/sweetalert.min.js"></script>
<script src="~/assets/js/pages/sweet-alert/sweet-alert-data.js"></script>

<!DOCTYPE html>
<html>
    <div class="row">
        @if (TempData["msg"] != null)
        {
            @Html.Raw(TempData["msg"])
        }
        <div class="col-md-12">
            <div class="card card-topline-green">
                <div class="card-head">
                    <header>INSTRUCTORES DE EDUCACIÓN CONTINUA</header>
                    <div class="tools">
                        <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                        <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                        <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="row p-b-20">
                        <div class="col-md-6 col-sm-6 col-6">
                            <div class="btn-group">
                                <a asp-controller="AcademicosInstructorEduContinua" asp-action="Crear" class="btn btn-success btn-sm m-b-10">
                                    Agregar <i class="fa fa-plus" style="color:white"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="table-scrollable">
                        <table class="table table-striped table-bordered table-hover table-checkable order-column" style="width: 100%" id="EduContinua">
                            <thead>
                                <tr>
                                    <th hidden></th>
                                    <th class="center"> Número de personal </th>
                                    <th class="center"> Nombre del académico</th>
                                    <th class="center"> Nombre del ingreso </th>
                                    <th class="center"> Ingreso </th>
                                    <th class="center"> Periodo </th>
                                    <th class="center"> Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="odd gradeX">
                                        <td hidden></td>
                                        <td>@Html.DisplayFor(modelItem => item.NumPersonal)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</td>
                                        <td>@Html.DisplayFor(modelItem => item.NomIngreso)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Ingreso)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Periodo)</td>
                                        <td class="center">
                                            <a asp-route-id="@item.IdInstructorEdu" asp-controller="AcademicosInstructorEduContinua" asp-action="Editar" class="btn btn-primary btn-xs editardatos" title="Editar">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            <a data-value="@item.IdInstructorEdu" data-controlador="AcademicosInstructorEduContinua" data-accion="Eliminar" data-regreso="Index" name="eliminardato" class="btn btn-danger btn-xs" title="Eliminar">
                                                <i class="fa fa-trash-o "></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</html>