Models/TablaMatPE.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SGCFIEE.Models
{
    public class TablaMatPE
    {
        public int idMapa { get; set; }
        public String nomMat { get; set; }
        public int idPE { get; set; }
        public String area { get; set; }
        public int creditos { get; set; }
        public int idEE { get; set; }
        public int estado { get; set; }
    }
}

Controllers/AcademicosComplementariaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SGCFIEE.Models;

namespace SGCFIEE.Controllers
{
    // aqui se encuentran todos los catalogos del sistema
    // de esta forma los usuarios pueden hacer cambios en el futuro
    // siempre es necesario obtener el id del tipo de usuario que esta haciendo las solicutudes
    // ya que solo el administrador debe tener acceso a esa parte

    // vista principal con los catálogos
    public class AcademicosComplementariaController : Controller
    {
        [Authorize]
        public IActionResult VistaOpcionesCatalogos()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            return View();
        }




        [Authorize]
        // muestra los tipos de localización: local, nacional, internacional 
        public IActionResult MostrarLocalizacion()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            List<TipoLocNacInter> loc = new List<TipoLocNacInter>();
            using (sgcfieeContext context = new sgcfieeContext())
            {
                loc = context.TipoLocNacInter.ToList();
            }
            return View(loc);
        }
        [Authorize]
        public IActionResult InsertarLocalizacion()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GuardarLocalizacion(TipoLocNacInter datos)
        {
            // verificamos que los datos no sean repetidos
            using (sgcfieeContext context = new sgcfieeContext())
            {
                var info = context.TipoLocNacInter.ToList();
                foreach(TipoLocNacInter item in info)
                {
                    if(item.Nombre == datos.Nombre)
                    {   // retornamos un mensaje cuando los datos ya existan
                        TempData["msg"] = "<script language='javascript'> swal({ title:'" + "La información ya se encuentra registrada!" + "', timer:'" + "3500" + "',type: '" + "info" + "', showConfirmButton: false })" + "</script>";
                        return RedirectToAction("MostrarLocalizacion");
                    }
                }
            }
            // guardamos los datos
            using (sgcfieeContext context = new sgcfieeContext())
            {
                context.TipoLocNacInter.Add(datos);
                context.SaveChanges();
                TempData["msg"] = "<script language='javascript'> swal({ title:'" + "Guardado exitosamente!" + "', timer:'" + "2000" + "',type: '" + "success" + "', showConfirmButton: false })" + "</script>";
            }
            return RedirectToAction("MostrarLocalizacion");
        }
        [Authorize]
        // obtenemos el id del registro a Editar
        public IActionResult EditarLocalizacion(int id)
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                TipoLocNacInter datos = context.TipoLocNacInter.Where(s => s.IdTipo == id).Single();
                return View(datos);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ActualizarLocalizacion(TipoLocNacInter datos)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                // verificamos que los datos no sean repetidos
                var info = context.TipoLocNacInter.Where(i => i.IdTipo != datos.IdTipo).ToList();
                foreach (TipoLocNacInter item in info)
                {
                    if (item.Nombre == datos.Nombre)
                    {
                        TempData["msg"] = "<script language='javascript'> swal({ title:'" + "La información ya se encuentra registrada!" + "', timer:'" + "3500" + "',type: '" + "info" + "', showConfirmButton: false })" + "</script>";
                        return RedirectToAction("MostrarLocalizacion");
                    }
                }
            }
            // guardamos los datos
            using (sgcfieeContext context = new sgcfieeContext())
            {
                context.TipoLocNacInter.Update(datos);
                context.SaveChanges();
                TempData["msg"] = "<script language='javascript'> swal({ title:'" + "Actualizado exitosamente!" + "', timer:'" + "2000" + "',type: '" + "success" + "', showConfirmButton: false })" + "</script>";
            }
            return RedirectToAction("MostrarLocalizacion");
        }
        public IActionResult EliminarLocalizacion(int id)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                TipoLocNacInter eliminar = context.TipoLocNacInter.Where(s => s.IdTipo == id).Single();
                context.TipoLocNacInter.Remove(eliminar);
                context.SaveChanges();
            }
            return RedirectToAction("MostrarLocalizacion");
        }



        [Authorize]
        public IActionResult MostrarEditorial()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            List<Editorial> edit = new List<Editorial>();
            using (sgcfieeContext context = new sgcfieeContext())
            {
                edit = context.Editorial.ToList();
            }
            return View(edit);
        }
        [Authorize]
        public IActionResult InsertarEditorial()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult GuardarEditorial(Editorial datos)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                // verificamos que los datos no sean repetidos
                var info = context.Editorial.ToList();
                foreach (Editorial item in info)
                {
                    if (item.Nombre == datos.Nombre)
                    {
                        TempData["msg"] = "<script language='javascript'> swal({ title:'" + "La información ya se encuentra registrada!" + "', timer:'" + "3500" + "',type: '" + "info" + "', showConfirmButton: false })" + "</script>";
                        return RedirectToAction("MostrarEditorial");
                    }
                }
            }
            // se guardan los datos
            using (sgcfieeContext context = new sgcfieeContext())
            {
                context.Editorial.Add(datos);
                context.SaveChanges();
                TempData["msg"] = "<script language='javascript'> swal({ title:'" + "Guardado exitosamente!" + "', timer:'" + "2000" + "',type: '" + "success" + "', showConfirmButton: false })" + "</script>";
            }
            return RedirectToAction("MostrarEditorial");
        }
        [Authorize]
        public IActionResult EditarEditorial(int id)
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                Editorial datos = context.Editorial.Where(s => s.IdEditorial == id).Single();
                return View(datos);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ActualizarEditorial(Editorial datos)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                // verificamos que los datos no sean repetidos
                var info = context.Editorial.Where(e => e.IdEditorial != datos.IdEditorial).ToList();
                foreach (Editorial item in info)
                {
                    if (item.Nombre == datos.Nombre)
                    {
                        TempData["msg"] = "<script language='javascript'> swal({ title:'" + "La información ya se encuentra registrada!" + "', timer:'" + "3500" + "',type: '" + "info" + "', showConfirmButton: false })" + "</script>";
                        return RedirectToAction("MostrarEditorial");
                    }
                }
            }
            // guardamos los datos
            using (sgcfieeContext context = new sgcfieeContext())
            {
                context.Editorial.Update(datos);
                context.SaveChanges();
                TempData["msg"] = "<script language='javascript'> swal({ title:'" + "Actualizado exitosamente!" + "', timer:'" + "2000" + "',type: '" + "success" + "', showConfirmButton: false })" + "</script>";
            }
            return RedirectToAction("MostrarEditorial");
        }
        public IActionResult EliminarEditorial(int id)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                Editorial eliminar = context.Editorial.Where(s => s.IdEditorial == id).Single();
                context.Editorial.Remove(eliminar);
                context.SaveChanges();
            }
            return RedirectToAction("MostrarEditorial");
        }

        [Authorize]
        // nivel jerarquico de los cuerpos académicos
        public IActionResult MostrarNivel()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            List<CanivelJerarquico> nivel = new List<CanivelJerarquico>();
            using (sgcfieeContext context = new sgcfieeContext())
            {
                nivel = context.CanivelJerarquico.ToList();
            }
            return View(nivel);
        }
        [Authorize]
        public IActionResult InsertarNivel()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");

Views/AcademicosComplementaria/CrearSalon.cshtml
@model SGCFIEE.Models.TbSalones
@{


    ViewData["Title"] = "Crear Salon";
    Layout = "~/Views/Home/Principal.cshtml";
}

<!DOCTYPE html>

<html>
<div class="profile-content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-topline-green">
                    <div class="card-head">
                        <header>Información de los salones</header>
                    </div>
                </div>
                <div class="white-box">
                    
                    <div class="tab-content">
                        <div class="tab-pane fontawesome-demo active show" id="tab1">
                            <form asp-action="CrearSalon" asp-antiforgery="true">
                                <div class="row">
                                    <div class="col-md-12 col-sm-12">
                                        
                                        <div class="card-body " id="bar-parent2">
                                            <div class="row">

                                                <div class="col-md-6 col-sm-6">
                                                    <div class="form-group">
                                                        <label asp-for="Edificio">Edificio</label>
                                                        <input asp-for="Edificio" type="text" class="form-control" placeholder="Ingresar..." required="required">
                                                        <span asp-validation-for="Edificio" class="text-danger"></span>
                                                    </div>

                                                </div>
                                                <div class="col-md-6 col-sm-6">
                                                    <div class="form-group">
                                                        <label asp-for="ClaveSalon">Número del salon</label>
                                                        <input asp-for="ClaveSalon" type="text" class="form-control" placeholder="Ingresar..." required="required">
                                                        <span asp-validation-for="ClaveSalon" class="text-danger"></span>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 col-sm-12">
                                        <div class="card-body " id="bar-parent2">
                                            <div class="row">
                                                <div class="col-md-6 col-sm-6">
                                                    <a asp-controller="AcademicosComplementaria" asp-action="MostrarSalon" class="btn btn-success btn-sm m-b-10">
                                                        Mostrar tabla
                                                    </a>
                                                </div>
                                                <div class="col-md-6 col-sm-6">
                                                    <input id="enviasa" type="submit" value="Guardar" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                    <a asp-controller="AcademicosComplementaria" asp-action="VistaOpcionesCatalogos" class="btn btn-default btn-sm m-b-10" style="float:right">
                                                        Cancelar
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</html>

Views/AcademicosComplementaria/EditarModalidad.cshtml
@model SGCFIEE.Models.TipoModalidad;
@{
    Layout = "~/Views/Home/Principal.cshtml";
}

<!DOCTYPE html>

<html>
<div class="profile-content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-topline-green">
                    <div class="card-head">
                        <header>Modalidad de trabajos recepcionales</header>
                    </div>
                </div>
                <div class="white-box">
                    <div class="tab-content">
                        <div class="tab-pane fontawesome-demo active show" id="tab1">
                            <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    <div class="card-body " id="bar-parent2">
                                        <!-- text input -->
                                        <form asp-action="ActualizarModalidad" asp-antiforgery="true">
                                            <div class="card-body " id="bar-parent2">
                                                <div class="row">
                                                    <input type="hidden" asp-for="IdModalidad" />
                                                    <div class="col-md-3 col-sm-3"></div>
                                                    <div class="col-md-6 col-sm-6">
                                                        <div class="form-group">
                                                            <label >Nombre de la modalidad: </label>
                                                            <input asp-for="Nombre" type="text" class="form-control" placeholder="Ingresar..." required="required">
                                                            <span asp-validation-for="Nombre" class="text-danger"></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3"></div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12 col-sm-12">
                                                    <div class="card-body " id="bar-parent2">
                                                        <div class="row">
                                                            <div class="col-md-6 col-sm-6">
                                                    
                                                            </div>
                                                            <div class="col-md-6 col-sm-6">
                                                                <button type="submit" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                                    Guardar
                                                                </button>
                                                                <a asp-controller="AcademicosComplementaria" asp-action="MostrarModalidad" id="cancelarEdicion" class="btn btn-default btn-sm m-b-10" style="float:right">
                                                                    Cancelar
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</html>

Views/AcademicosComplementaria/EditarProducto.cshtml
@model SGCFIEE.Models.TipoEvaluador;
@{
    Layout = "~/Views/Home/Principal.cshtml";
}

<!DOCTYPE html>

<html>
<div class="profile-content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-topline-green">
                    <div class="card-head">
                        <header>Producto a evaluar</header>
                    </div>
                </div>
                <div class="white-box">
                    
                    <div class="tab-content">
                        <div class="tab-pane fontawesome-demo active show" id="tab1">
                            <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    <div class="card-body " id="bar-parent2">
                                        <!-- text input -->
                                        <form asp-action="ActualizarProducto" asp-antiforgery="true">
                                            <div class="card-body " id="bar-parent2">
                                                <div class="row">
                                                    <input type="hidden" asp-for="IdTipoEvaluador" />
                                                    <div class="col-md-3 col-sm-3"></div>
                                                    <div class="col-md-6 col-sm-6">
                                                        <div class="form-group">
                                                            <label >Nombre del producto: </label>
                                                            <input asp-for="Nombre" type="text" class="form-control" placeholder="Ingresar..." required="required">
                                                            <span asp-validation-for="Nombre" class="text-danger"></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3"></div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12 col-sm-12">
                                                    <div class="card-body " id="bar-parent2">
                                                        <div class="row">
                                                            <div class="col-md-6 col-sm-6">
                                                    
                                                            </div>
                                                            <div class="col-md-6 col-sm-6">
                                                                <button type="submit" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                                    Guardar
                                                                </button>
                                                                <a asp-controller="AcademicosComplementaria" asp-action="MostrarProducto" id="cancelarEdicion" class="btn btn-default btn-sm m-b-10" style="float:right">
                                                                    Cancelar
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</html>

Views/AcademicosComplementaria/EditarTipoe.cshtml
@model SGCFIEE.Models.TipoEventos
@{
    ViewData["Title"] = "Editar Tipo eventos";
    Layout = "~/Views/Home/Principal.cshtml";
}


<!DOCTYPE html>

<html>
<div class="profile-content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-topline-green">
                    <div class="card-head">
                        <header>Tipo de evento</header>
                    </div>
                </div>
                <div class="white-box">
                    
                    <div class="tab-content">
                        <div class="tab-pane fontawesome-demo active show" id="tab1">
                            <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    
                                    <div class="card-body " id="bar-parent2">
                                        <!-- text input -->
                                        <form asp-action="EditarTipoe" asp-antiforgery="true">
                                            <div class="card-body " id="bar-parent2">
                                                <div class="row">
                                                    <input asp-for="IdEventos" value="@Model.IdEventos" hidden />
                                                    <div class="col-md-3 col-sm-3"></div>
                                                    <div class="col-md-6 col-sm-6">
                                                        <div class="form-group">
                                                            <label asp-for="Nombre">Nombre del tipo de evento</label>
                                                            <input asp-for="Nombre" type="text" class="form-control" placeholder="Ingresar..." required="required">
                                                            <span asp-validation-for="Nombre" class="text-danger"></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3"></div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12 col-sm-12">
                                                    <div class="card-body " id="bar-parent2">
                                                        <div class="row">
                                                            <div class="col-md-6 col-sm-6">
                                                                
                                                            </div>
                                                            <div class="col-md-6 col-sm-6">
                                                                <input type="submit" value="Guardar" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                                <a asp-controller="AcademicosComplementaria" asp-action="MostrarTipoe" class="btn btn-default btn-sm m-b-10" style="float:right">
                                                                    Cancelar
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</html>

Views/AcademicosComplementaria/FormEditarDistincion.cshtml
@model SGCFIEE.Models.TipoDistincionTa;
@{
    Layout = "~/Views/Home/Principal.cshtml";
}

<!DOCTYPE html>

<html>
<div class="profile-content">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="card">
                <div class="card-topline-green">
                    <div class="card-head">
                        <header>Distinciones al trabajo académico</header>
                    </div>
                </div>
                <div class="white-box">
                    <div class="tab-content">
                        <div class="tab-pane fontawesome-demo active show" id="tab1">
                            <div class="row">
                                <div class="col-md-12 col-sm-12">
                                    <div class="card-body " id="bar-parent2">
                                        <!-- text input -->
                                        <form asp-action="EditarDistincion" asp-antiforgery="true">
                                            <div class="card-body " id="bar-parent2">
                                                <div class="row">
                                                    <input type="hidden" asp-for="IdDistincion" />
                                                    <div class="col-md-3 col-sm-3"></div>
                                                    <div class="col-md-6 col-sm-6">
                                                        <div class="form-group">
                                                            <label asp-for="Nombre">Nombre de la distinción: </label>
                                                            <input asp-for="Nombre" id="idpafi" type="text" class="form-control" placeholder="Ingresar..." required="required">
                                                            <span asp-validation-for="Nombre" class="text-danger"></span>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3 col-sm-3"></div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12 col-sm-12">
                                                    <div class="card-body " id="bar-parent2">
                                                        <div class="row">
                                                            <div class="col-md-6 col-sm-6">
                                                    
                                                            </div>
                                                            <div class="col-md-6 col-sm-6">
                                                                <button type="submit" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                                    Guardar
                                                                </button>
                                                                <a asp-controller="AcademicosComplementaria" asp-action="MostrarDistincionesTA" id="cancelarEdicion" class="btn btn-default btn-sm m-b-10" style="float:right">
                                                                    Cancelar
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</html>