Controllers/AcademicosParticipacionesAcadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SGCFIEE.Models;
using System.Diagnostics;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Fiver.Mvc.FileUpload.Models.Home;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SGCFIEE.Controllers
{
    public class AcademicosParticipacionesAcadController : Controller
    {
        // GET: /<controller>/
        [Authorize]
        //Función para mostrar la información de los Arbitraje de productos académicos que presentan los académicos.
        public IActionResult IndexArbitraje()
        {
            int tipoUsu = (int)HttpContext.Session.GetInt32("TipoUsuario"); //tipo es la variable donde se guarda el permiso según tipo de usuario (1=director, 2=académico, 3=alumno).
            int idUsu = (int)HttpContext.Session.GetInt32("IdUsu"); //idUsu guarda al ID del usuario segun la tabla de usuario de la base de datos.
            //La clase TablaEvaluadores fue creada manualmente, esto para poder tener acceso a los datos de un solo lugar.
            List<TablaEvaluadores> ListEvaluadores = new List<TablaEvaluadores>(); //Declaración de la lista donde se obtendran los datos.
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Consulta para obtener a todos los academicos con sus respectivos Arbitraje de productos académicos.
                ListEvaluadores = (from datos in context.EvaluadoresAcademicos
                                   join tipo in context.TipoEvaluador on datos.IdTipoEvaluador equals tipo.IdTipoEvaluador
                                   select new TablaEvaluadores
                                   {
                                       IdEvaluadores = datos.IdEvaluadoresAcademicos,
                                       Archivo = datos.Archivo,
                                       Tipo = tipo.Nombre,
                                       RevisorEvaluador = datos.RevisorEvaluador,
                                       StatusEvaluador = datos.Status
                                   }
                               ).ToList();
                if (tipoUsu == 2)
                {
                    //Si el usuario es de tipo 2 (académico), se consulta si es lider de algun Arbitraje y darle el permiso de modificar dichos registros.
                    List<Academicosevaluadores> ListAcad = new List<Academicosevaluadores>();
                    ListAcad = context.Academicosevaluadores.Where(w => w.IdAcademico == idUsu && w.Lider == 1).ToList();
                    ViewData["ListAcad"] = ListAcad;
                }
            }
            return View(ListEvaluadores);
        }
        [Authorize]
        //Función para acceder a la vista de agregar el arbitraje y obtener los datos necesarios para los select.
        public IActionResult CrearArbitraje()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                var acad = context.Academicos.ToList(); //Obtención de los academicos de la base de datos.
                var tipo = context.TipoEvaluador.ToList(); //Obtención de los tipos de evaluadores de la base de datos.
                //Envio de datos a la vista por medio del diccionario ViewData.
                ViewData["academicos"] = acad;
                ViewData["evaluadores"] = tipo;
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        //Función para guardar los datos obtenidos de la vista de crear arbitraje de productos académicos.
        public async Task<IActionResult> GuardarArbitraje(IFormFile file, EvaluadoresAcademicos datos, int idAcademico, int Lider)
        {
            int tipo = (int)HttpContext.Session.GetInt32("TipoUsuario"); //tipo es la variable donde se guarda el permiso según tipo de usuario (1=director, 2=académico, 3=alumno).
            if (tipo == 2)
            {
                //Si el tipo de usuario es = 2 (académico), aquí se obtinen el id del académico, ya que en los datos obtenidos de la vista no viene.
                idAcademico = (int)HttpContext.Session.GetInt32("IdUsu");
            }
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Ahora se verifica que la información a guardar no se encuentre ya registrada en la tabla "EvaluadoresAcademicos".
                var ListEvaluador = context.EvaluadoresAcademicos.ToList(); //Se obtienen los registros de la tabla.
                foreach (EvaluadoresAcademicos item in ListEvaluador)
                {
                    //Se comparan los datos ha guardar con cada registro obtenido anteriormente. Si se comple la condición, se redireccionara al index y no se guardaran los datos.
                    if (datos.IdTipoEvaluador == item.IdTipoEvaluador && datos.RevisorEvaluador == item.RevisorEvaluador)
                    {
                        TempData["msg"] = "<script language='javascript'> swal({ title:'" + "La información ya se encuentra registrada!" + "', timer:'" + "3500" + "',type: '" + "info" + "', showConfirmButton: false })" + "</script>";
                        return RedirectToAction("IndexArbitraje");
                    }
                }
            }
            using (sgcfieeContext context = new sgcfieeContext())
            {
                var name = file.GetFilename();
                datos.Archivo = name;
                context.EvaluadoresAcademicos.Add(datos); //Guardado de la información.
                context.SaveChanges();
                EvaluadoresAcademicos DatosEval = context.EvaluadoresAcademicos.Last(); //Se obtiene el registro anteriormente guardado, para poder modificar el nombre del archivo y evitar sobre escritura.
                var new_name_table = DatosEval.IdEvaluadoresAcademicos + "_" + file.GetFilename(); //Modificación del nombre del archivo, para evitar la sobreescritura con otros.
                datos.Archivo = new_name_table;
                context.EvaluadoresAcademicos.Update(datos); //Actualización de la información.
                context.SaveChanges();
            }

            if (file == null || file.Length == 0)
                return Content("file not selected");

            var new_name_file = datos.IdEvaluadoresAcademicos + "_" + file.GetFilename(); //Modificación del nombre del archivo, para evitar la sobreescritura con otros.
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Archivos/ParticipacionAcad/Arbitraje", new_name_file); //Se acompleta la ruta del archivo.
            //Guardado del archivo.
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Se guarda al académico creador del arbitraje en la tabla Academicosevaluadores.
                EvaluadoresAcademicos DatosCT = context.EvaluadoresAcademicos.Last();
                Academicosevaluadores info = new Academicosevaluadores();
                info.IdAcademico = idAcademico;
                info.IdEvaluadores = DatosCT.IdEvaluadoresAcademicos; //Guardado de la información.
                info.Lider = Lider;
                context.Academicosevaluadores.Add(info); 
                context.SaveChanges();
                TempData["msg"] = "<script language='javascript'> swal({ title:'" + "Guardado exitosamente!" + "', timer:'" + "2000" + "',type: '" + "success" + "', showConfirmButton: false })" + "</script>";
            }
            return RedirectToAction("IndexArbitraje");
        }
        [Authorize]
        //Función para acceder a la vista de editar el arbitraje y obtener los datos necesarios para los select.
        public IActionResult EditarArbitraje(int id)
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Obtención de los datos a editar.
                EvaluadoresAcademicos DatosEvaluadores = context.EvaluadoresAcademicos.Where(s => s.IdEvaluadoresAcademicos == id).Single();


                var tipo = context.TipoEvaluador.ToList(); //Obtención de los tipos de evaluador de la base de datos.
                //Envio de datos a la vista por medio del diccionario ViewData.
                ViewData["evaluadores"] = tipo;
                return View(DatosEvaluadores);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        //Función para actualizar los datos obtenidos de la vista de editar arbitraje de productos académicos.
        public async Task<IActionResult> ActualizarArbitraje(IFormFile file, EvaluadoresAcademicos datos)
        {
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Ahora se verifica que la información a actualizar no se encuentre ya registrada en la tabla "EvaluadoresAcademicos".
                var ListEvaluador = context.EvaluadoresAcademicos.Where(e => e.IdEvaluadoresAcademicos != datos.IdEvaluadoresAcademicos).ToList(); //Se obtienen los registros de la tabla.
                foreach (EvaluadoresAcademicos item in ListEvaluador)
                {
                    //Se comparan los datos ha actualizar con cada registro obtenido anteriormente. Si se comple la condición, se redireccionara al index y no se actualizaran los datos.
                    if (datos.IdTipoEvaluador == item.IdTipoEvaluador && datos.RevisorEvaluador == item.RevisorEvaluador)

Views/AcademicosParticipacionesAcad/AcademicosArbitraje.cshtml
@model  IEnumerable<SGCFIEE.Models.TablaAcadArbitraje> 
@{
    ViewData["Title"] = "AcadArticulos";
    Layout = "~/Views/Home/Principal.cshtml";
    var acade = (IEnumerable<Academicos>)ViewData["academicos"];
    var Acad = (Academicosevaluadores)ViewData["Acad"];
    var tipo = (int)ViewData["tipo"];
}
<link rel="stylesheet" href="~/assets/plugins/sweet-alert/sweetalert.min.css">
<script src="~/assets/plugins/sweet-alert/sweetalert.min.js"></script>
<script src="~/assets/js/pages/sweet-alert/sweet-alert-data.js"></script>
<!DOCTYPE html>
<html>
    <div class="row">
        @if (TempData["msg"] != null)
        {
            @Html.Raw(TempData["msg"])
        }
        <div class="col-md-12 col-sm-12">
            <div class="card card-box">
                <div class="card-topline-green card-head">
                    <header>COLABORADORES</header>
                </div>
                <div class="white-box">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div id="Artículos">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="card-body ">
                                            
                                                @if (Acad != null || tipo == 1)
                                                {
                                                    <form asp-controller="AcademicosParticipacionesAcad" asp-action="GuardarAcadArbitraje" method="post" enctype="multipart/form-data">
                                                        <input name="arbitraje" value="@ViewData["idArbitraje"]" type="hidden"/>
                                                        <input name="Lider" value="0" type="hidden"/>
                                                        <div class="row p-b-20">
                                                            <div class="col-md-4 col-md-4">
                                                                <div class="form-group">
                                                                    <label>Académico</label>
                                                                    <select name="idAcademico" class="form-control">
                                                                        @foreach (var item in acade)
                                                                        {
                                                                            <option value="@item.IdAcademicos">@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</option>
                                                                        }
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row p-b-20">
                                                            <div class="col-md-2 col-sm-6 col-2">
                                                                <div class="btn-group">
                                                                    <button type="submit" class="btn btn-success btn-sm m-b-10" name="Guardar" style="float:right">
                                                                        Académico<i class="fa fa-plus" style="color:white"></i>
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                }
                                            
                                            <div class="table-scrollable">
                                                <table class="table table-striped table-bordered table-hover table-checkable order-column"  style="width: 100%" id="TablaArticulos" >
                                                    <thead>
                                                        <tr>
                                                            <th hidden></th>
                                                            <th class="center"> Numero de personal</th>
                                                            <th class="center"> Nombre del académico</th>
                                                            @if(tipo == 2)
                                                            {
                                                                @if (Acad != null)
                                                                {
                                                                    <th class="center"> Acción</th>
                                                                }
                                                            }
                                                            @if(tipo == 1)
                                                            {
                                                                <th class="center"> Acción</th>
                                                            }
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td hidden></td>
                                                                <td>@Html.DisplayFor(modelItem => item.NumPersonal)</td>
                                                                <td>@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</td>
                                                                @if (tipo == 2)
                                                                {
                                                                    @if (Acad != null)
                                                                    {
                                                                        <td class="center">
                                                                            <a data-value="@item.IdAcadEvaluadores" data-id="@item.idEvaluadores" data-controlador="AcademicosParticipacionesAcad" data-accion="EliminarAcadArbitraje" data-regreso="AcademicosArbitraje" name="eliminaracademico" class="btn btn-danger btn-xs" title="Eliminar">
                                                                                <i class="fa fa-trash-o "></i>
                                                                            </a>
                                                                        </td>
                                                                    }
                                                                }
                                                                @if (tipo == 1)
                                                                {
                                                                    <td class="center">
                                                                        <a data-value="@item.IdAcadEvaluadores" data-id="@item.idEvaluadores" data-controlador="AcademicosParticipacionesAcad" data-accion="EliminarAcadArbitraje" data-regreso="AcademicosArbitraje" name="eliminaracademico" class="btn btn-danger btn-xs" title="Eliminar">
                                                                            <i class="fa fa-trash-o "></i>
                                                                        </a>
                                                                    </td>
                                                                }
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                            <a asp-controller="AcademicosParticipacionesAcad" asp-action="IndexArbitraje" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                Regresar
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</html>

<script src="~/assets/js/pages/table/table_data.js"></script>

Views/AcademicosParticipacionesAcad/AcademicosCursos_Talleres.cshtml
@model  IEnumerable<SGCFIEE.Models.TablaAcadCursoTalleres> 
@{
    ViewData["Title"] = "AcadArticulos";
    Layout = "~/Views/Home/Principal.cshtml";
    var acade = (IEnumerable<Academicos>)ViewData["academicos"];
    var Acad = (Academicoscursostaller)ViewData["Acad"];
    var tipo = (int)ViewData["tipo"];
}
<link rel="stylesheet" href="~/assets/plugins/sweet-alert/sweetalert.min.css">
<script src="~/assets/plugins/sweet-alert/sweetalert.min.js"></script>
<script src="~/assets/js/pages/sweet-alert/sweet-alert-data.js"></script>
<!DOCTYPE html>
<html>
    <div class="row">
        @if (TempData["msg"] != null)
        {
            @Html.Raw(TempData["msg"])
        }
        <div class="col-md-12 col-sm-12">
            <div class="card card-box">
                <div class="card-topline-green card-head">
                    <header>COLABORADORES</header>
                </div>
                <div class="white-box">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div id="Artículos">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="card-body ">
                                            
                                                @if (Acad != null || tipo == 1)
                                                {
                                                    <form asp-controller="AcademicosParticipacionesAcad" asp-action="GuardarAcadCursos_Talleres" method="post" enctype="multipart/form-data">
                                                        <input name="cursotaller" value="@ViewData["idCursoTaller"]" type="hidden"/>
                                                        <input name="Lider" value="0" type="hidden"/>
                                                        <div class="row p-b-20">
                                                            <div class="col-md-4 col-md-4">
                                                                <div class="form-group">
                                                                    <label>Académico</label>
                                                                    <select name="idAcademico" class="form-control">
                                                                        @foreach (var item in acade)
                                                                        {
                                                                            <option value="@item.IdAcademicos">@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</option>
                                                                        }
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row p-b-20">
                                                            <div class="col-md-2 col-sm-6 col-2">
                                                                <div class="btn-group">
                                                                    <button type="submit" class="btn btn-success btn-sm m-b-10" name="Guardar" style="float:right">
                                                                        Académico<i class="fa fa-plus" style="color:white"></i>
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                }
                                            
                                            <div class="table-scrollable">
                                                <table class="table table-striped table-bordered table-hover table-checkable order-column"  style="width: 100%" id="TablaArticulos" >
                                                    <thead>
                                                        <tr>
                                                            <th hidden></th>
                                                            <th class="center"> Numero de personal</th>
                                                            <th class="center"> Nombre del académico</th>
                                                            @if(tipo == 2)
                                                            {
                                                                @if (Acad != null)
                                                                {
                                                                    <th class="center"> Acción</th>
                                                                }
                                                            }
                                                            @if(tipo == 1)
                                                            {
                                                                <th class="center"> Acción</th>
                                                            }
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td hidden></td>
                                                                <td>@Html.DisplayFor(modelItem => item.NumPersonal)</td>
                                                                <td>@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</td>
                                                                @if (tipo == 2)
                                                                {
                                                                    @if (Acad != null)
                                                                    {
                                                                        <td class="center">
                                                                            <a data-value="@item.IdAcadCursoTalleres" data-id="@item.idCursosTalleres" data-controlador="AcademicosParticipacionesAcad" data-accion="EliminarAcadCursos_Talleres" data-regreso="AcademicosCursos_Talleres" name="eliminaracademico" class="btn btn-danger btn-xs" title="Eliminar">
                                                                                <i class="fa fa-trash-o "></i>
                                                                            </a>
                                                                        </td>
                                                                    }
                                                                }
                                                                @if (tipo == 1)
                                                                {
                                                                    <td class="center">
                                                                        <a data-value="@item.IdAcadCursoTalleres" data-id="@item.idCursosTalleres" data-controlador="AcademicosParticipacionesAcad" data-accion="EliminarAcadCursos_Talleres" data-regreso="AcademicosCursos_Talleres" name="eliminaracademico" class="btn btn-danger btn-xs" title="Eliminar">
                                                                            <i class="fa fa-trash-o "></i>
                                                                        </a>
                                                                    </td>
                                                                }
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                            <a asp-controller="AcademicosParticipacionesAcad" asp-action="IndexCursos_Talleres" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                Regresar
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</html>

<script src="~/assets/js/pages/table/table_data.js"></script>