Models/AcademicosPatentes.cs
using System;
using System.Collections.Generic;

namespace SGCFIEE.Models
{
    public partial class Academicospatentes
    {
        public int IdAcademicosPatentes { get; set; }
        public int? IdAcademicos { get; set; }
        public int? IdPatentes { get; set; }
        public int? Lider { get; set; }

        public virtual Academicos IdAcademicosNavigation { get; set; }
        public virtual PatentesAcademicos IdPatentesNavigation { get; set; }
    }
}

Controllers/AcademicosPublicacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SGCFIEE.Models;
using System.Diagnostics;
using Fiver.Mvc.FileUpload.Models.Home;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using System.Globalization;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SGCFIEE.Controllers
{
    public class AcademicosPublicacionesController : Controller
    {
        // GET: /<controller>/
        [Authorize]
        //Función para mostrar la información de los articulos que presentan los académicos.
        public IActionResult IndexArticulos()
        {
            int tipoUsu = (int)HttpContext.Session.GetInt32("TipoUsuario"); //tipo es la variable donde se guarda el permiso según tipo de usuario (1=director, 2=académico, 3=alumno).
            int idUsu = (int)HttpContext.Session.GetInt32("IdUsu"); //idUsu guarda al ID del usuario segun la tabla de usuario de la base de datos.
            //La clase TablaArticulos fue creada manualmente, esto para poder tener acceso a los datos de un solo lugar.
            List<TablaArticulos> ListArticulos = new List<TablaArticulos>(); //Declaración de la lista donde se obtendran los datos
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Consulta para obtener a todos los academicos con sus respectivos articulos.
                ListArticulos = (from datos in context.Articulos
                                 join tipo in context.TipoLocNacInter on datos.IdTipoNI equals tipo.IdTipo
                                 select new TablaArticulos
                                 {
                                     IdArticulos = datos.IdArticulos,
                                     Archivo = datos.Archivo,
                                     Tipo = tipo.Nombre,
                                     Registro = datos.Registro,
                                     Arbitrada = datos.Arbitrada,
                                     NombreArticulo = datos.Nombre,
                                 }
                               ).ToList();
                if (tipoUsu == 2)
                {
                    //Si el usuario es de tipo 2 (académico), se consulta si es lider de algun articulo y darle el permiso de modificar dichos registros.
                    List<Academicoarticulos> ListAcad = new List<Academicoarticulos>();
                    ListAcad = context.Academicoarticulos.Where(w => w.IdAcademico == idUsu && w.Lider == 1).ToList();
                    ViewData["ListAcad"] = ListAcad;
                }
            }

            return View(ListArticulos);
        }
        [Authorize]
        //Función para acceder a la vista de agregar el  articulo de un académico y obtener los datos necesarios para los select.
        public IActionResult CrearArticulos()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                var acad = context.Academicos.ToList(); //Obtención de los academicos de la base de datos.
                var lugar = context.TipoLocNacInter.Where(s => s.Nombre != "Local").ToList(); //Obtención de los datos a editar.
                //Envio de datos a la vista por medio del diccionario ViewData.
                ViewData["academicos"] = acad;
                ViewData["lugar"] = lugar;
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        //Función para guardar los datos obtenidos de la vista de crear articulos.
        public async Task<IActionResult> GuardarArticulos(IFormFile file, Articulos datos, int idAcademico, int Lider)
        { 
            int tipo = (int)HttpContext.Session.GetInt32("TipoUsuario"); //tipo es la variable donde se guarda el permiso según tipo de usuario (1=director, 2=académico, 3=alumno).
            if (tipo == 2)
            {
                //Si el tipo de usuario es = 2 (académico), aquí se obtinen el id del académico, ya que en los datos obtenidos de la vista no viene.
                idAcademico = (int)HttpContext.Session.GetInt32("IdUsu");
            }
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Ahora se verifica que la información a guardar no se encuentre ya registrada en la tabla "Articulos".
                var ListArticulos = context.Articulos.ToList(); //Se obtienen los registros de la tabla.
                foreach (Articulos item in ListArticulos)
                {
                    //Se comparan los datos ha guardar con cada registro obtenido anteriormente. Si se comple la condición, se redireccionara al index y no se guardaran los datos.
                    if (datos.IdTipoNI == item.IdTipoNI && datos.Nombre == item.Nombre && datos.Registro == item.Registro && datos.Arbitrada == item.Arbitrada)
                    {
                        TempData["msg"] = "<script language='javascript'> swal({ title:'" + "La información ya se encuentra registrada!" + "', timer:'" + "3500" + "',type: '" + "info" + "', showConfirmButton: false })" + "</script>";
                        return RedirectToAction("IndexArticulos");
                    }
                }
            }
            using (sgcfieeContext context = new sgcfieeContext())
            {
                var name = file.GetFilename();
                datos.Archivo = name;
                context.Articulos.Add(datos); //Guardado de la información.
                context.SaveChanges();
                Articulos DatosArticulo = context.Articulos.Last(); //Se obtiene el registro anteriormente guardado, para poder modificar el nombre del archivo y evitar sobre escritura.
                var new_name_table = DatosArticulo.IdArticulos + "_" + file.GetFilename();
                datos.Archivo = new_name_table;
                context.Articulos.Update(datos); //Actualización de la información.
                context.SaveChanges();
            }

            if (file == null || file.Length == 0)
                return Content("file not selected");

            var new_name_file = datos.IdArticulos + "_" + file.GetFilename(); //Modificación del nombre del archivo, para evitar la sobreescritura con otros.
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Archivos/Publicaciones/Articulos", new_name_file); //Se acompleta la ruta del archivo.
            //Guardado del archivo.
            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Se guarda al académico creador del articulo en la tabla Academicoarticulos.
                Articulos DatosArticulo = context.Articulos.Last();
                Academicoarticulos info = new Academicoarticulos();
                info.IdAcademico = idAcademico;
                info.IdArticulo = DatosArticulo.IdArticulos;
                info.Lider = Lider;
                context.Academicoarticulos.Add(info); //Guardado de la información.
                context.SaveChanges();
                TempData["msg"] = "<script language='javascript'> swal({ title:'" + "Guardado exitosamente!" + "', timer:'" + "2000" + "',type: '" + "success" + "', showConfirmButton: false })" + "</script>";
            }
            return RedirectToAction("IndexArticulos");
        }
        [Authorize]
        //Función para mostrar la información de académicos colaboradores de un respectivo articulo seleccionado.
        public IActionResult AcademicosArticulos(int id)
        {
            int tipoUsu = (int)HttpContext.Session.GetInt32("TipoUsuario"); //tipoUsu es la variable donde se guarda el permiso según tipo de usuario (1=director, 2=académico, 3=alumno).
            int idUsu = (int)HttpContext.Session.GetInt32("IdUsu"); //idUsu guarda al ID del usuario segun la tabla de usuario de la base de datos.
            //La clase TablaAcadArticulos fue creada manualmente, esto para poder tener acceso a los datos de un solo lugar.
            List<TablaAcadArticulos> ListAcadArticulos = new List<TablaAcadArticulos>(); //Declaración de la lista donde se obtendran los datos.
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            using (sgcfieeContext context = new sgcfieeContext())
            {
                //Consulta para obtener a todos los academicos relacionados con el articulo.
                ListAcadArticulos = (from datos in context.Academicoarticulos
                                     join acad in context.Academicos on datos.IdAcademico equals acad.IdAcademicos
                                     where datos.IdArticulo == id
                                     select new TablaAcadArticulos
                                     {
                                         IdAcadArticulos = datos.IdAcademicoArticulos,
                                         NumPersonal = acad.NumeroPersonal,
                                         Nombre = acad.Nombre,
                                         ApellidoPaterno = acad.ApellidoPaterno,
                                         ApellidoMaterno = acad.ApellidoMaterno,
                                         idArticulo = datos.IdArticulo
                                     }
                                     ).ToList();
                var acade = context.Academicos.ToList();
                //Envio de los datos a la vista.

Controllers/AcademicosReportesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SGCFIEE.Models;
using System.Diagnostics;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SGCFIEE.Controllers
{
    public class AcademicosReportesController : Controller
    {
        // GET: /<controller>/
        [Authorize]
        public IActionResult Index()
        {
            ViewData["tipo"] = (int)HttpContext.Session.GetInt32("TipoUsuario");
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/AcademicosPublicaciones/AcademicosConcursos.cshtml
@model  IEnumerable<SGCFIEE.Models.TablaAcadConcursos> 
@{
    ViewData["Title"] = "AcadArticulos";
    Layout = "~/Views/Home/Principal.cshtml";
    var acade = (IEnumerable<Academicos>)ViewData["academicos"];
    var Acad = (Academicoconcursos)ViewData["Acad"];
    var tipo = (int)ViewData["tipo"];
}

<link rel="stylesheet" href="~/assets/plugins/sweet-alert/sweetalert.min.css">
<script src="~/assets/plugins/sweet-alert/sweetalert.min.js"></script>
<script src="~/assets/js/pages/sweet-alert/sweet-alert-data.js"></script>

<!DOCTYPE html>
<html>
    <div class="row">
        @if (TempData["msg"] != null)
        {
            @Html.Raw(TempData["msg"])
        }
        <div class="col-md-12 col-sm-12">
            <div class="card card-box">
                <div class="card-topline-green card-head">
                    <header>COLABORADORES</header>
                </div>
                <div class="white-box">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div id="Artículos">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="card-body ">
                                                @if (Acad != null || tipo == 1)
                                                {
                                                    <form asp-controller="AcademicosPublicaciones" asp-action="GuardarAcadConcursos" method="post" enctype="multipart/form-data">
                                                        <input name="concursos" value="@ViewData["idConcursos"]" type="hidden"/>
                                                        <input name="Lider" value="0" type="hidden"/>
                                                        <div class="row p-b-20">
                                                            <div class="col-md-4 col-md-4">
                                                                <div class="form-group">
                                                                    <label>Académico</label>
                                                                    <select name="idAcademico" class="form-control">
                                                                        @foreach (var item in acade)
                                                                        {
                                                                            <option value="@item.IdAcademicos">@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</option>
                                                                        }
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row p-b-20">
                                                            <div class="col-md-2 col-sm-6 col-2">
                                                                <div class="btn-group">
                                                                    <button type="submit" class="btn btn-success btn-sm m-b-10" name="Guardar" style="float:right">
                                                                        Académico<i class="fa fa-plus" style="color:white"></i>
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                }
                                            <div class="table-scrollable">
                                                <table class="table table-striped table-bordered table-hover table-checkable order-column"  style="width: 100%" id="TablaArticulos" >
                                                    <thead>
                                                        <tr>
                                                            <th hidden></th>
                                                            <th class="center"> Numero de personal</th>
                                                            <th class="center"> Nombre del académico</th>
                                                            @if(tipo == 2)
                                                            {
                                                                @if (Acad != null)
                                                                {
                                                                    <th class="center"> Acción</th>
                                                                }
                                                            }
                                                            @if(tipo == 1)
                                                            {
                                                                <th class="center"> Acción</th>
                                                            }
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td hidden></td>
                                                                <td>@Html.DisplayFor(modelItem => item.NumPersonal)</td>
                                                                <td>@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</td>
                                                                @if (tipo == 2)
                                                                {
                                                                    @if (Acad != null)
                                                                    {
                                                                        <td class="center">
                                                                            <a data-value="@item.IdAcadConcursos" data-id="@item.IdConcursos" data-controlador="AcademicosPublicaciones" data-accion="EliminarAcadConcursos" data-regreso="AcademicosConcursos" name="eliminaracademico" class="btn btn-danger btn-xs" title="Eliminar">
                                                                                <i class="fa fa-trash-o "></i>
                                                                            </a>
                                                                        </td>
                                                                    }
                                                                }
                                                                @if (tipo == 1)
                                                                {
                                                                    <td class="center">
                                                                        <a data-value="@item.IdAcadConcursos" data-id="@item.IdConcursos" data-controlador="AcademicosPublicaciones" data-accion="EliminarAcadConcursos" data-regreso="AcademicosConcursos" name="eliminaracademico" class="btn btn-danger btn-xs" title="Eliminar">
                                                                            <i class="fa fa-trash-o "></i>
                                                                        </a>
                                                                    </td>
                                                                }
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                            <a asp-controller="AcademicosPublicaciones" asp-action="IndexConcursos" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                Regresar
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</html>

<script src="~/assets/js/pages/table/table_data.js"></script>

Views/AcademicosPublicaciones/AcademicosLibros.cshtml
@model  IEnumerable<SGCFIEE.Models.TablaAcadLibros> 
@{
    ViewData["Title"] = "AcadArticulos";
    Layout = "~/Views/Home/Principal.cshtml";
    var acade = (IEnumerable<Academicos>)ViewData["academicos"];
    var Acad = (Academicolibro)ViewData["Acad"];
    var tipo = (int)ViewData["tipo"];
}

<link rel="stylesheet" href="~/assets/plugins/sweet-alert/sweetalert.min.css">
<script src="~/assets/plugins/sweet-alert/sweetalert.min.js"></script>
<script src="~/assets/js/pages/sweet-alert/sweet-alert-data.js"></script>

<!DOCTYPE html>
<html>
    <div class="row">
        @if (TempData["msg"] != null)
        {
            @Html.Raw(TempData["msg"])
        }
        <div class="col-md-12 col-sm-12">
            <div class="card card-box">
                <div class="card-topline-green card-head">
                    <header>COLABORADORES</header>
                </div>
                <div class="white-box">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div id="Artículos">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="card-body ">
                                                @if (Acad != null || tipo == 1)
                                                {
                                                    <form asp-controller="AcademicosPublicaciones" asp-action="GuardarAcadLibros" method="post" enctype="multipart/form-data">
                                                        <input name="libros" value="@ViewData["idLibros"]" type="hidden"/>
                                                        <input name="Lider" value="0" type="hidden"/>
                                                        <div class="row p-b-20">
                                                            <div class="col-md-4 col-md-4">
                                                                <div class="form-group">
                                                                    <label>Académico</label>
                                                                    <select name="idAcademico" class="form-control">
                                                                        @foreach (var item in acade)
                                                                        {
                                                                            <option value="@item.IdAcademicos">@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</option>
                                                                        }
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row p-b-20">
                                                            <div class="col-md-2 col-sm-6 col-2">
                                                                <div class="btn-group">
                                                                    <button type="submit" class="btn btn-success btn-sm m-b-10" name="Guardar" style="float:right">
                                                                        Académico<i class="fa fa-plus" style="color:white"></i>
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </form>
                                                }
                                            
                                            <div class="table-scrollable">
                                                <table class="table table-striped table-bordered table-hover table-checkable order-column"  style="width: 100%" id="TablaArticulos" >
                                                    <thead>
                                                        <tr>
                                                            <th hidden></th>
                                                            <th class="center"> Numero de personal</th>
                                                            <th class="center"> Nombre del académico</th>
                                                            @if(tipo == 2)
                                                            {
                                                                @if (Acad != null)
                                                                {
                                                                    <th class="center"> Acción</th>
                                                                }
                                                            }
                                                            @if(tipo == 1)
                                                            {
                                                                <th class="center"> Acción</th>
                                                            }
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td hidden></td>
                                                                <td>@Html.DisplayFor(modelItem => item.NumPersonal)</td>
                                                                <td>@Html.DisplayFor(modelItem => item.Nombre) @Html.DisplayFor(modelItem => item.ApellidoPaterno) @Html.DisplayFor(modelItem => item.ApellidoMaterno)</td>
                                                                @if (tipo == 2)
                                                                {
                                                                    @if (Acad != null)
                                                                    {
                                                                        <td class="center">
                                                                            <a data-value="@item.IdAcadLibros" data-id="@item.IdLibros" data-controlador="AcademicosPublicaciones" data-accion="EliminarAcadLibros" data-regreso="AcademicosLibros" name="eliminaracademico" class="btn btn-danger btn-xs" title="Eliminar">
                                                                                <i class="fa fa-trash-o "></i>
                                                                            </a>
                                                                        </td>
                                                                    }
                                                                }
                                                                @if (tipo == 1)
                                                                {
                                                                    <td class="center">
                                                                        <a data-value="@item.IdAcadLibros" data-id="@item.IdLibros" data-controlador="AcademicosPublicaciones" data-accion="EliminarAcadLibros" data-regreso="AcademicosLibros" name="eliminaracademico" class="btn btn-danger btn-xs" title="Eliminar">
                                                                            <i class="fa fa-trash-o "></i>
                                                                        </a>
                                                                    </td>
                                                                }
                                                            </tr>
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                            <a asp-controller="AcademicosPublicaciones" asp-action="IndexLibros" class="btn btn-success btn-sm m-b-10" style="float:right">
                                                Regresar
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</html>

<script src="~/assets/js/pages/table/table_data.js"></script>